// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTrackingAPI.Data;

#nullable disable

namespace TimeTrackingAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimeTrackingAPI.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "WEB-01",
                            CreatedAt = new DateTime(2026, 6, 24, 12, 29, 32, 155, DateTimeKind.Utc).AddTicks(5615),
                            IsActive = true,
                            Name = "Разработка веб-платформы"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MOB-01",
                            CreatedAt = new DateTime(2026, 6, 24, 12, 29, 32, 155, DateTimeKind.Utc).AddTicks(5625),
                            IsActive = true,
                            Name = "Мобильное приложение"
                        },
                        new
                        {
                            Id = 3,
                            Code = "SUP-01",
                            CreatedAt = new DateTime(2026, 6, 24, 12, 29, 32, 155, DateTimeKind.Utc).AddTicks(5626),
                            IsActive = false,
                            Name = "Техническая поддержка"
                        });
                });

            modelBuilder.Entity("TimeTrackingAPI.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 24, 12, 29, 32, 155, DateTimeKind.Utc).AddTicks(5712),
                            IsActive = true,
                            Name = "Разработка API",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 24, 12, 29, 32, 155, DateTimeKind.Utc).AddTicks(5716),
                            IsActive = true,
                            Name = "Дизайн интерфейса",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 24, 12, 29, 32, 155, DateTimeKind.Utc).AddTicks(5717),
                            IsActive = true,
                            Name = "Тестирование",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 24, 12, 29, 32, 155, DateTimeKind.Utc).AddTicks(5718),
                            IsActive = true,
                            Name = "Разработка iOS",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 24, 12, 29, 32, 155, DateTimeKind.Utc).AddTicks(5719),
                            IsActive = false,
                            Name = "Разработка Android",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 24, 12, 29, 32, 155, DateTimeKind.Utc).AddTicks(5720),
                            IsActive = false,
                            Name = "Консультации клиентов",
                            ProjectId = 3
                        });
                });

            modelBuilder.Entity("TimeTrackingAPI.Models.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Hours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EntryDate");

                    b.HasIndex("TaskId");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("TimeTrackingAPI.Models.Task", b =>
                {
                    b.HasOne("TimeTrackingAPI.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TimeTrackingAPI.Models.TimeEntry", b =>
                {
                    b.HasOne("TimeTrackingAPI.Models.Task", "Task")
                        .WithMany("TimeEntries")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TimeTrackingAPI.Models.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TimeTrackingAPI.Models.Task", b =>
                {
                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
